### ISSUE TITLE
Do not disable DocumentsUi.

### ISSUE THREAD

**Issue by laltroweb** [Magisk-Modules-Alt-Repo/MiXplorer#11]
This module disable/remove documentsui and this cause more issue with many other apps.

**Comment by hg42** [comment]
it causes **severe** issues...
it's not possible to grant permissions to storage directories without it, because documentsui provides the directory selector for it.

Even more, MiXplorer itself needs it for getting access to storage.
On my phone, after installing the module, MiXplorer couldn't access internal storage, because it had to be granted again (MiXplorer was uninstalled before).
Testing with installing over an already existent MiXplorer doesn't show the problem.

**Comment by hg42** [comment]
I'm not sure, but it looks like replacing DocumentsUI is a method to install MiXplorer as system app?
Because I tried release 6.58.4 (without any date attached) and it doesn't seem to work on my A10 ROM. "Files" is there but no MiXplorer.
With the later versions MiXPlorer is there but Files is missing (if the module is enabled and after a reboot).

**Comment by txdevs** [comment]
This module replaces DocumentsUI and DocumentsUIGoogle with empty folders.

DocumentsUI is required - Android API 30+ uses Storage Access Framework (SAF), which requires DocumentsUI to grant access to the device storage.

Until the module is updated, you can manually fix it:

1. Extract the module zip.

2. Delete the entire "priv-app" folder in system/ within the extracted module folder.

3. Re-zip the module folders.

4. Make sure when you open your zip, the following folders/file are in the root of the zip, and not an additional folder:

/META-INF
/system
module.prop

5. Install your modified zip in Magisk Manager.

**Comment by laltroweb** [comment]
No reply by dev, and also with customized zip issue come back at every update. Maybe i can try to make a fork.

**Comment by laltroweb** [comment]
Forked release. 👍

**Comment by Fox2Code** [comment]
This module should not replaces DocumentsUI and DocumentsUIGoogle with empty folders.
This is because Android architecture relies on DocumentsUI for the storage access framework.
This is even more important since recent Android versions do not allows direct file access.

**Comment by hg42** [comment]
I once got a notification about a fork by @laltroweb but I don't see it? what happened?

**Comment by hg42** [comment]
> 2. Delete the entire "priv-app" folder in system/ within the extracted module folder.

Thanks, this works for me.

I simply used an archiver that can modify a zip directly and deleted that folder.

Actually, I already tried this before and I don't have a clue why it failed.

**Comment by Atrate** [comment]
> No broken modules (doesn't do what it says it will, or doesn't define correctly compatible devices).

@Psk-Ita Please fix your module or we'll need to delete your repository until it's all good, the issues presented here are severe to say the least.

**Comment by Fox2Code** [comment]
@Atrate Can I ping you on GitHub when I see something broken?
Also do you have any way to be contacted outside of GitHub or do you prefer not being contacted outside of GitHub?

Also I think it would be a good idea to add into this repo rule:
- "We may perform changes without developer approval on any broken modules that is abandoned by it's original developer"

**Comment by Atrate** [comment]
> @Atrate Can I ping you on GitHub when I see something broken?

Only if the author is inactive and it's a simple fix, otherwise I see no reason to keep deprecated, broken modules.

>  Also do you have any way to be contacted outside of GitHub or do you prefer not being contacted outside of GitHub?

Yes, you can e-mail me, you can find my e-mail in the signoff in my commits and my PGP key in my profile if you'd like to use that.

> Also I think it would be a good idea to add into this repo rule:

Agreed.

**Comment by laltroweb** [comment]
> > @Atrate Can I ping you on GitHub when I see something broken?
> 
> Only if the author is inactive and it's a simple fix, otherwise I see no reason to keep deprecated, broken modules.
> 
> > Also do you have any way to be contacted outside of GitHub or do you prefer not being contacted outside of GitHub?
> 
> Yes, you can e-mail me, you can find my e-mail in the signoff in my commits and my PGP key in my profile if you'd like to use that.
> 
> > Also I think it would be a good idea to add into this repo rule:
> 
> Agreed, @Fox2Code .

Tu so much for tried, but dev comeback and with new release insert same but.
So, this plugin can be considered as dead.

**Comment by Atrate** [comment]
@Psk-Ita This starts to look like malicious actions. If you don't respond and fix your module, it will be deleted in 3 days (if I forget, someone ping me).

**Comment by Atrate** [comment]
Alright, I see you've fixed that, thanks. I'd recommend cleaning up the issues now, as there's quite a few about the same problem.

**Comment by 0E800** [comment]
Using current release, still has issues when trying to select and enable storage folders using PowerAmp and EX Kernel Manager. Once module is disabled the apps are able to access storage. Is there a way to link DocumentUI to another file manager or make Mixplorer it's replacement?

**Comment by GraciousGpal** [comment]
Eugh i finally found that it was this module causing all of the issues with DocumentUi. This is still not fixed or the author rolled it back.

> Alright, I see you've fixed that, thanks. I'd recommend cleaning up the issues now, as there's quite a few about the same problem.
> 
> [a989106](https://github.com/Magisk-Modules-Alt-Repo/MiXplorer/commit/a9891063c691bd0a7c5736eb58c5a5138e9a3f4c)

Eugh I finally found out that it was this module causing all of the issues with DocumentUi. At least state in the module description that it is modifying it. When this module is enabled it causes documentUi to crash. (Android 13)

**Comment by hg42** [comment]
I don't understand why Mixplorer should try to replace DocumentsUI, especially because it is **NOT** able to do this (**it doesn't provide the necessary file selector and grant permission part**)

**Comment by 0E800** [comment]
> I don't understand why Mixplorer should try to replace DocumentsUI, especially because it is **NOT** able to do this (**it doesn't provide the necessary file selector and grant permission part**)

Only suggested as in some cases documentsui doesn't work when this mod is applied. Documentsui seems to be a file choser or bridge, there's a file manager on fdroid that is able to work in place when documentsui is missing.

**Comment by GraciousGpal** [comment]
> file manager on fdroid

Can you give me the name for this file manager ?

**Comment by hg42** [comment]
as far as I know there is no file manager that can replace DocumentsUI.

Mist people forget thee second functionality:

1. DocumentsUI serves as file manager. It can access SAF storage, which means Google Drive and other SAF provider.
Most file managers can not **access** SAF storage at all, though some like Mixplorer can (when you create a new Storage entry, you can choose from Documents Provider).

2. DocumentsUI provides the File selection for **granting access** to any SAF storage, this includes a real sdcard and usb storage but also remote storage. It's the only offiicial way for an app to access everything **outside** of "Internal Storage" but also to gain **access to folders inside** Internal Storage.

Without DocumentsUI any apps that store files outside their own data directories and need to use SAF for it (which is the current standard on any Android) cannot gain access to those folders.
Then the only way to access such files is by either using root commands (thus root file managers work) or by granting access to everything in the ROM or by some extension (Xposed, Magisk, etc.).

**Comment by sunmughan** [comment]
I need a files and documentsui fix to use this module. Can't compromise. Your module is good but causing troubles while accessing saf folders during several operation. It is creating mess. I want to know ehy your module is trying to replace the documentsui ?

**Comment by Psk-Ita** [comment]
new build introduce a kind of interactive setup
user can choose to persist or remove FilesPrebuild, DocumentsUI and Google DocumentsUI

**Comment by Ahplla** [comment]
The problem persists, which is surreal.

How can a repository of this caliber allow the use of the highly regarded name of Mix Explorer and ruin it miserably?

Even with interactive installation, the module breaks DocumentsUi. With or without persist it breaks one way or another.

Could someone more qualified please assist the Dev of this module or appropriate it?

**Comment by hg42** [comment]
I still don't understand why someone might want to remove DocumentsUI and now also two other ROM level "Files" apps...

However, I see, you can say yes via volume up button (three times) to "persist DocumentsUI" and the other two. So, the dev did find a solution to fit different desires.

Though, I would suggest to move the removal function to a separate package.
I am quite sure, it's only a very special case, when you want to remove the DocumentsUI functionality.

As a contributor dev of the NeoBackup app I can say, that we had quite a few users complaining about not being able to get access to their backup folder because of this. And I think there are much more, that don't complain, but think, NeoBackup does not work.

**Comment by Ahplla** [comment]
> I still don't understand why someone might want to remove DocumentsUI and now also two other ROM level "Files" apps...
> 
> However, I see, you can say yes via volume up button (three times) to "persist DocumentsUI" and the other two. So, the dev tried to find a solution to fit different desires.
> 
> Though, I would suggest to move the removal function to a separate package. I am quite sure, it's only a very special case, when you want to remove the DocumentsUI functionality.
> 
> As a contributor dev of the NeoBackup app I can say, that we had quite a few users complaining about not being able to get access to their backup folder because of this. And I think there are much more, that don't complain, but think, NeoBackup does not work.

What the dev left doesn't work.  Keep or not is returning the same errors and I have a theory.  When MiXplore is installed as a system app, either manually or via this magisk module, it crashes the essential native Android file app.

I suspect it's due to library incompatibility.  As MiXplorer is, even if systemless, installed in "system/app", DocumentsUi or DocumentsUiGoogle prefers to use MiXplorer's libs instead of their own or Android's.

That said, I'm going to invert the original hierarchy of folders and see what happens.
