### ISSUE TITLE
Unable to install on Windows Subsystem for Android

### ISSUE THREAD

**Issue by nerd-king** [Magisk-Modules-Alt-Repo/MiXplorer#17]
I'm trying to install on WSA, and the script just fails because it doesn't detect volume keys to answer the questions.  Is there an alternative method for answering questions when volume keys are not present? I tried running magisk --install-module from a root terminal but same thing occurs.

**Comment by EleoXDA** [comment]
Why not use standalone apk files shared in XDA thread of Mixplorer? The rest is available in playstore. Or you can just purchase Mixplorer Silver package and have them all ready in playstore

**Comment by Psk-Ita** [comment]
@nerd-king 
just unzip the module, navigate to it's content, then install the apks files you prefer
