### ISSUE TITLE
Ongoing maintenance

### ISSUE THREAD

**Issue by ertmuirm** [Magisk-Modules-Alt-Repo/MiXplorer#2]
Thanks for uploading this. I used MiXplorer as well and it's great. Will you be updating this module regularly as MiXplorer receives official updates?

And will this install MiXplorer in the system partition? What are the benefits from installing via the zip instead of the apk?

**Comment by Psk-Ita** [comment]
Ciao,
the read-me file explain a bit the reason of this module (basically to have a full setup, in one shot)
while setting-up stufs I used the module approach for debloating existing files-manages to keep my device clean

I am not connected with MiXplorer developers (https://github.com/mixplorer), but, yes, I'll try to keep the module updated
