### ISSUE TITLE
Playstore updates of MiX Metadata and SMB

### ISSUE THREAD

**Issue by EleoXDA** [Magisk-Modules-Alt-Repo/MiXplorer#27]
![Screenshot_20230503-151632.png](https://user-images.githubusercontent.com/27622683/235941794-06c11d5e-a472-46f5-b23a-7bc931ac689d.png)

It is not that disturbing, but is it possible to remove the playstore link from MiX Metadata and MiX SMB so that they do not get recognized to be updated?

**Comment by Psk-Ita** [comment]
Ciao,
you have to do it by yourself, you can check [this module](https://github.com/j-hc/mindetach-magisk) 

in the detach.txt file wrire
`com.mixplorer.addon.image
com.mixplorer.addon.pdf
com.mixplorer.addon.archive
com.mixplorer.addon.codecs
com.mixplorer.addon.autotag
com.mixplorer.addon.tagger
com.mixplorer.addon.metadata
com.mixplorer.addon.signer
com.mixplorer.addon.smb
com.mixplorer.beta
com.mixplorer`

this is the full list, you can add all, or just the one you prefer to be hidden from playstore
