### ISSUE TITLE
Module isn't showing as installed with KSU

### ISSUE THREAD

**Issue by FunkyNico** [Magisk-Modules-Alt-Repo/MiXplorer#29]
Hey there, i just noticed that when you install this module with Kernel SU it installs just fine and even after the reboot you have the app installed, but it doesn't show up as a module on KSU Manager. Hope it can be fixed. Thanks.

**Comment by Psk-Ita** [comment]
Ciao
this is not an issue
module just collects all MiXplorer features and install them forma you
if you want remove it, (totally or just some features) just search mixplorer on installed apps and do it your-serf

**Comment by dxcvvxd** [comment]
the problem with this is that even with magisk it doesnt show up as installed NOR does it install mixplorer, maybe it deletes itself halfway through? bad code?

**Comment by datsoy** [comment]
Not all apps  in module is installed after installing in kernelsu.
Only 3 apps remain.

![Screenshot_20240126-174706_SD Maid](https://github.com/Magisk-Modules-Alt-Repo/MiXplorer/assets/67457715/92caa9c5-cb7e-4fb8-8d48-180020fb8ead)
