### ISSUE TITLE
Addons Update Playstore Error

### ISSUE THREAD

**Issue by KelvinCrag** [Magisk-Modules-Alt-Repo/MiXplorer#3]
The following applications refuse to get updated after asking for update on playstore:

MiX metadata (MiXplorer Add-on)
MiX SMB 2.0/2.1 (MiXplorer Add-on)

![Screenshot_20220304-094334~2](https://user-images.githubusercontent.com/64832927/156729954-a49c0874-d313-4615-9719-ca7c8ffb5462.png)

**Comment by Ahplla** [comment]
same

**Comment by 0ldb34r** [comment]
Same here

**Comment by Psk-Ita** [comment]
this is a fake error, add-ons are updated to latest available version from MiXplorer repo (settings, add-on, add)
the playstore just detect you are running this asset coming from outside the playstore
trying a different store-client (AuroraStore for exaple) does not detect updates
