### ISSUE TITLE
Not working A14 Aosp GSI rom magisk canary zygisk

### ISSUE THREAD

**Issue by ArSd-g** [Magisk-Modules-Alt-Repo/MiXplorer#30]
Totally useless; install then reboot = nothing; disapear from magisk modules, and no icon launcher in "apps".
Update or Close this repo that makes me loose 1h of m'y life ;)
[magisk_install_log_2024-02-19T18.02.39.log](https://github.com/Magisk-Modules-Alt-Repo/MiXplorer/files/14335132/magisk_install_log_2024-02-19T18.02.39.log)

**Comment by lovwanshichetan** [comment]
Just flash any older version or manually install by unzipping older version for now.
Note: now this module flashes as user app only not system, so it will not show in your installed modules section but it's wired that the app icon hadn't appeared on apps screen.

**Comment by Psk-Ita** [comment]
not sure why, but it seems downloading apk at runtime may not work properly
package now has all resources embedded (it should work as expected now)
