### ISSUE TITLE
Breaks files AOSP files app

### ISSUE THREAD

**Issue by KelvinCrag** [Magisk-Modules-Alt-Repo/MiXplorer#5]
Cannot allow sdcard usage when using the module.

**Comment by Agent4-SplatnetRus** [comment]
Also some apps say they _"cannot find Storage Access Framework compatible file manager"_ and refuses to let user choose directory needed for app to work. Disabling magisk module without uninstalling Mixplorer seems to fix this. 

(This seems to be the same problem, so I decided not to open new issue)

**Comment by Psk-Ita** [comment]
the new build includes an interactive setup
users can select to remove or persist Out-Of-The-Box embedded file managers
