### ISSUE TITLE
Files app gets replaced (hidden)

### ISSUE THREAD

**Issue by mgood7123** [Magisk-Modules-Alt-Repo/MiXplorer#6]
this module currently `.replace` documentui and related folders

**Comment by MikaelaMuller** [comment]
Yeah just had the same issue on my Samsung Galaxy A5 2017 running Lineage 19.1 Android 12

**Comment by Psk-Ita** [comment]
I did initially to clean-up system, avoiding having duplicate apps for the same purpose
due to "Android Storage Access Framework" the module's setup, will allow you to choose, for:
- FilesPrebuild
- DocumentsUI
- DocumentsUIGoogle
to persist or remove them

**Comment by Psk-Ita** [comment]
Nice to hear this

as usual: Enjoy!

;)
