### ISSUE TITLE
Bootloop

### ISSUE THREAD

**Issue by ammlr** [Magisk-Modules-Alt-Repo/MiXplorer#7]
I experienced a bootloop after flashing your module. then it booted successfully when I flashed the factory boot. but strangely why when flashing patched image always bootloop? 

this seems to be the effect of your module. how to fix it? .

**Comment by Ahplla** [comment]
I'm having the same bootloop problems, it seems to be connected with having some MiXplorer plugin already installed from Playstore.

**Comment by laltroweb** [comment]
Bootlop also for me. Saved from bootlop protector.

**Comment by Ahplla** [comment]
At pixel 5 I get stuck on startup forever on Google's G

**Comment by africabloe** [comment]
I do not recommend this module.
Bootloop on my device for the first time after 2 years of flashing roms and kernels.
I powered OFF. Restarted to Recovery 
ROOT >> DATA >> ADB >> MODULES >> delete Mixplorer folder
Everything is fine now
